### ISSUE TITLE
Clarify which user to authenticate if userHandle is not present

### ISSUE THREAD

**Issue by milesstoetzner** [w3c/webauthn#1078]
Maybe one should clarify Step 2 of [Verifying an authentication assetion](https://www.w3.org/TR/webauthn/#verifying-assertion) for the case, that userHandle is not present:

>2. If credential.response.userHandle is present, verify that the user identified by this value is the owner of the public key credential identified by credential.id.
**If credential.response.userHandle is not present, the owner of the public key credential identified by credential.id is the user to authenticate.**

Greetings, 
Miles

**Comment by emlun** [comment]
Hm, you have a point. I'll take a look at it.

**Comment by milesstoetzner** [comment]
I think the issue has been resolved, therefore I am closing this issue.

**Comment by emlun** [comment]
Has it been resolved without PR #1082 merged?

**Comment by milesstoetzner** [comment]
No, #1082 solved the problem, that I had in mind. Thanks for that :)

**Comment by emlun** [comment]
In that case this is not yet resolved, since #1082 is not yet merged. :)

**Comment by emlun** [comment]
Should we also add @milesstoetzner to [§15. Acknowledgements][ack]?

[ack]: https://w3c.github.io/webauthn/#acknowledgements
