### ISSUE TITLE
Allow immediate mediation

### ISSUE THREAD

**Issue by deephand** [w3c/webauthn#2228]
## Proposed Change

I added [an explainer](https://github.com/w3c/webauthn/wiki/Explainer:-WebAuthn-immediate-mediation) in the wiki that suggests to return a `NotFoundError` when there are no locally available credentials and otherwise show the modal UI. This should allow RPs to go formless and skip the hybrid flow, which is time consuming and not always applicable.

I would like to hear your opinions about it, thanks in advance!

**Comment by Firstyear** [comment]
You assume everyone will have access to passkeys to support this. The reality is not all users will be able to access passkeys (android famously errors to create passkeys without a full device reset), and some users may choose not to use them (due to not having a pw manager, unable due to rk limits on security keys, or distrust of apple/google). So you need to keep your username field for the foreseeable future.

**Comment by kenrb** [comment]
FYI: @deephand has updated the explainer with some clarifications. In particular:

1. It makes it clearer that the expectation is not for sites to be able to remove other sign-in options. The idea is that users with immediately-available passkeys can be shown the passkey UI directly without having to interact with a sign-in form, while users without those would see the same sign-in options that they do without this.
2. The privacy section now provides better detail on the compromise that we are proposing. The earlier version of the explainer was not explicit on this point. This would make a change to the privacy guarantees that the WebAuthn API currently provides, and the explainer offers mitigations intended to prevent any potential abuse of that change.

**Comment by ricea** [comment]
Sites can use that extra bit of information to lock out users who have credentials for the site but don't want to log in for whatever reason. A few sites like Twitter and Instagram show some content to logged-out users but aggressively try to coerce them to log in. With this feature they could be even more obnoxious.

Requiring user interaction seems worthless as a hurdle in an age where every site has cookie banners.

If there was a way to restrict this only to scenarios where the user was going to have to log in anyway, the privacy concerns would be lessened.

I can also see a usability problem when the account I want to log in to Twitter with is a different one from the one that my browser knows about.

**Comment by kenrb** [comment]
> Sites can use that extra bit of information to lock out users who have credentials for the site but don't want to log in for whatever reason. A few sites like Twitter and Instagram show some content to logged-out users but aggressively try to coerce them to log in. With this feature they could be even more obnoxious.

I agree this is a concern. Sites do this now using cookies, but this would make that problem somewhat worse because users who have manually clear their cookies might still have the existence of a sign-in credential apparent to the site through this mechanism. This is part of the reasoning why this feature would not work in private browsing modes such as incognito. It provides a way for users to hide the existence of credentials.
 
> I can also see a usability problem when the account I want to log in to Twitter with is a different one from the one that my browser knows about.

Yes. If you have two accounts, and one has a credential that will appear in this UI and one does not, then this adds friction signing in with the second account. That's a trade-off.

**Comment by ricea** [comment]
> Sites do this now using cookies, but this would make that problem somewhat worse because users who have manually cleared their cookies might still have the existence of a sign-in credential apparent to the site through this mechanism.

It's also an issue because of sync. I sync my personal browser profile between home and work, so they have access to the same credentials, but there are some sites I only log into at home. If I happen to access the same site at work, I don't particularly want it knowing that it knows me.

This could maybe be addressed by having some record of sites I have logged into that is intentionally not synced between machines. This would be consistent with how cookies work now, so maybe not too surprising?

**Comment by timcappalli** [comment]
WebAuthn hybrid meeting on 2025-04-11: there is multi-implementer interest in exploring this feature for L4.

**Comment by kenrb** [comment]
@rmondello Thank you for the response.

If the promise doesn't resolve in the case where there are no credentials, then I believe this becomes almost identical to the [Ambient UI proposal](https://github.com/w3c/webauthn/wiki/Explainer:-WebAuthn-Ambient-Signin-UI) (which hasn't been fully developed, but is something we are still thinking about).

The two proposals are intended to address different use cases. The goal with Immediate is to provide the site a way to trigger WebAuthn UI if a passkey is present, or provide a different option to the user (such as a traditional sign-in page, or a different signed-out experience) if one is not present. For example: Without leaking the existence of a credential, it would not be possible for a site to do a WebAuthn call directly in response to a user's click on a "Sign In" button on the site's home page, resulting in an in-context sign-in.

Ambient would allow sites to attempt to (conditionally) trigger WebAuthn browser UI at an arbitrary time (on a sign-in page, on the home page, or wherever). Immediate aims specifically to enable a conditional trigger in response to a user action, and in particular where the site wants the semantics of "show passkey sign-in UI, _or_ do something else".  That isn't possible without the information leakage that we are discussing, but in our view the use case is compelling enough to warrant the trade-off.

> With this kind of change made to the proposal, I can see Apple getting fully onboard.

Understood. If this is Apple's response to the request for a standards position, can that be added to [the issue](https://github.com/WebKit/standards-positions/issues/504)?

**Comment by rmondello** [comment]
> [@rmondello](https://github.com/rmondello) Thank you for the response.
> 
> If the promise doesn't resolve in the case where there are no credentials, then I believe this becomes almost identical to the [Ambient UI proposal](https://github.com/w3c/webauthn/wiki/Explainer:-WebAuthn-Ambient-Signin-UI) (which hasn't been fully developed, but is something we are still thinking about).
> 
> The two proposals are intended to address different use cases. The goal with Immediate is to provide the site a way to trigger WebAuthn UI if a passkey is present, or provide a different option to the user (such as a traditional sign-in page, or a different signed-out experience) if one is not present. For example: Without leaking the existence of a credential, it would not be possible for a site to do a WebAuthn call directly in response to a user's click on a "Sign In" button on the site's home page, resulting in an in-context sign-in.

I can see how the shape of what I’m proposing for “immediate” and the ambient proposal are isomorphic, but since the intended use case and behavior in the UA are so different, they’re different, right?

> Ambient would allow sites to attempt to (conditionally) trigger WebAuthn browser UI at an arbitrary time (on a sign-in page, on the home page, or wherever). Immediate aims specifically to enable a conditional trigger in response to a user action, and in particular where the site wants the semantics of "show passkey sign-in UI, _or_ do something else". That isn't possible without the information leakage that we are discussing, but in our view the use case is compelling enough to warrant the trade-off.

I think it would be OK to load a sign-in page behind the modal that comes up when a user clicks “Sign In”. I think in some testing that Google did in the past, having sign-in related content behind browser UI actually improved sign-in success rates.

Can you tell me more about what isn’t possible without the feedback to the RP?

**Comment by rmondello** [comment]
> > I think it would be OK to load a sign-in page behind the modal that comes up when a user clicks “Sign In”. I think in some testing that Google did in the past, having sign-in related content behind browser UI actually improved sign-in success rates.
> 
> Thanks for expanding on the idea of what immediate mediation might look like without leaking whether a user has a credential for the site. But the thought came to mind that this could probably also be achieved today by simply having the Sign In button take the user to `/signin` and then call `.get()` on page load. Which, if true, could obviate the need for immediate mediation...

It doesn’t! Because you’ll still get Hybrid’d. The goal is to only show credentials that are local, and then have a “Passkey” button on the page that will make a full request, including Hybrid.

**Comment by kenrb** [comment]
@MasterKale 
> Would the try -> catch -> navigate to login/ pattern be so bad for user privacy if there's a chance that the ceremony, with allowCredentials: [] which doesn't reveal anything on its own, simply failed because the user's credential was on a security key in the other room/in a locked credential manager vault that was just too finicky to quickly unlock/etc...? The fact that the proposal takes a usernameless-centric stance on how to invoke immediate mediation doesn't seem as fingerprint-y as to whether the user has an account on the site or not.

I believe the main concern is the situation in which the user has a passkey available and UI is shown, but they decline to sign in with that passkey. The site learns that the user has a passkey available, and likely _could_ have signed in with an existing account.

If no UI is shown, then that doesn't reveal much to the site. There are several reasons why that might happen even for a user who has an account.

The concern being discussed hasn't been about user fingerprinting. In the first case (UI is shown, user dismisses it) the site obtains information that in some cases would be unavailable to it today. It's not a lot of information (one bit, more or less), but the point has been made that it would be difficult for a user to hide it.

The question here and in the TAG review has been whether the sign-in experiences that this enables are a reasonable trade-off that leakage, in particular when compared to the best possible alternatives that don't provide information.

> Question to @kenrb, does "transient activation" require intentional clicking of something on the page? Would e.g. scrolling the page count as transient activation?

Scrolling does not provide an activation. I believe it requires a `mousedown`, `keydown`, or the completion of a touch event on mobile.

**Comment by kenrb** [comment]
@timcappalli I'd have no objection.

**Comment by diegomarcostre** [comment]
We at Amazon participated in the Origin Trial for immediate mediation with passkeys. The API lets users sign in to their accounts without leaving the main storefront, which provides a much smoother shopping journey. During the Origin Trial, we saw a decrease in average time to sign-in and an increase in sign-in success rate with the experiment group. We are planning to expand this feature to more sign-in flows and hope that all browsers adopt this API.

**Comment by kenrb** [comment]
As an update, this is currently available in Stable Chrome. https://developer.chrome.com/blog/webauthn-immediate-ui

**Comment by rmondello** [comment]
It is concerning and disappointing to see this move forward in Stable Chrome without having paid mind to the privacy feedback given by Apple. It is possible to deliver a large part of the value of the proposal without leaking the information to websites about whether you have a saved credential or not.

**Comment by akshayku** [comment]
I am also concerned about the privacy leak. In this case, in pursuit of best user experience, we are unfortunately compromising the privacy. Not every scenario/user experience needs to be supported fully.
